name: zuhaitz-fat
base: core22
version: '0.2.0'
summary: A TUI file and archive viewer for your terminal.
description: |
  FAT is a modern, TUI-based file and archive viewer for your terminal.
  It's designed for developers and power users who want to quickly inspect
  files and peek inside archives like .zip and .tar without having to
  extract them first. It is lightweight, fast, and highly extensible.

grade: stable
confinement: classic

apps:
  fat:
    command: usr/local/bin/command-fat.sh
    plugs:
      - home
      - removable-media
      - desktop

parts:
  fat:
    plugin: make
    source: .
    override-build: |
      make release
      make install DESTDIR=$CRAFT_PART_INSTALL
      cp snap/local/command-fat.sh $CRAFT_PART_INSTALL/usr/local/bin/
      chmod +x $CRAFT_PART_INSTALL/usr/local/bin/command-fat.sh
      craftctl default
    build-packages:
      - build-essential
      - gcc
      - make
      - libmagic-dev
      - libncursesw5-dev
      - libzip-dev
      - libtar-dev
    stage-packages:
      - libmagic1
      - libncursesw6
      - libzip4
      - libtinfo6
      - libtar0
